#!/usr/bin/env bash
# Generates config.js from .env — run once after cloning on EC2

set -e

if [ ! -f .env ]; then
  echo "ERROR: .env not found. Copy .env.example to .env and fill in your keys."
  exit 1
fi

source .env

cat > config.js <<EOF
// GoKwik — Merchant Product Radar · Configuration
// Generated by setup.sh from .env — do not commit this file.

window.GK_CONFIG = {
  METABASE_URL:      '${METABASE_URL:-https://internal-stats.gokwik.in}',
  METABASE_API_KEY:  '${METABASE_API_KEY:-}',
  ANTHROPIC_API_KEY: '${ANTHROPIC_API_KEY:-}',
};
EOF

echo "config.js written."
echo "Start the server with: python3 server.py"
